import type { AuditResult, TrustedRunSnapshot } from "./audit";
import type { ChallengePreview, PlanValidation, ResolutionPlan } from "./investigation";
export const HUMAN_AUTHORITY_STATEMENT = "A researcher, not WebMCP or JARVIS, confirms evidence and approves the exact plan. No experiment is executed automatically.";
export type DecisionBrief = { schemaVersion: "1.0"; status: "draft" | "approved" | "approved_with_limitation"; watermark: "DRAFT — NOT APPROVED" | "AUTHORITATIVE"; comparisonDigest: string; question: string; runs: Array<{ id: string; name: string; metric: { name: string; value: number } }>; findings: AuditResult["findings"]; citations: AuditResult["evidence_refs"]; researcherChallenge: ChallengePreview | null; plan: ResolutionPlan | null; planValidation: PlanValidation | null; planBinding: { version: number; digest: string } | null; approval: { status: string; approvedAt: string; rationale: string; approvedBy: string | null; acknowledgedLimitations?: string[] } | null; humanAuthorityStatement: typeof HUMAN_AUTHORITY_STATEMENT };
export type BriefInput = { question: string; comparisonDigest: string; runs: readonly TrustedRunSnapshot[]; audit: AuditResult; challenge?: ChallengePreview | null; plan?: ResolutionPlan | null; validation?: PlanValidation | null; binding?: { version: number; digest: string } | null; approval?: DecisionBrief["approval"] };
export function createDecisionBrief(input: BriefInput): DecisionBrief {
  const approved = Boolean(input.approval && input.binding);
  const status = approved ? (input.approval!.status === "approved_with_limitation" ? "approved_with_limitation" : "approved") : "draft";
  return { schemaVersion: "1.0", status, watermark: approved ? "AUTHORITATIVE" : "DRAFT — NOT APPROVED", comparisonDigest: input.comparisonDigest, question: input.question,
    runs: input.runs.map((run) => ({ id: run.id, name: run.name, metric: { name: run.metric_name, value: run.metric_value } })), findings: input.audit.findings,
    citations: input.audit.evidence_refs, researcherChallenge: input.challenge ?? null, plan: input.plan ?? null, planValidation: input.validation ?? null,
    planBinding: input.binding ?? null, approval: input.approval ?? null, humanAuthorityStatement: HUMAN_AUTHORITY_STATEMENT };
}
export function renderDecisionBriefMarkdown(brief: DecisionBrief): string {
  return ["# Research audit decision brief", "", `> ${brief.watermark}`, "", `**Status:** ${brief.status}`, `**Comparison digest:** \`${brief.comparisonDigest}\``, "", "## Decision question", "", brief.question, "", "## Runs and metrics", "", ...brief.runs.map((run) => `- ${run.name}: ${run.metric.name} = ${run.metric.value}`), "", "## Findings", "", ...brief.findings.flatMap((finding) => [`### ${finding.title} (${finding.severity})`, "", finding.summary, `Citations: ${finding.evidence_ref_ids.join(", ") || "none"}`, ""]), "## Researcher challenge", "", brief.researcherChallenge?.researcherContext ?? "Not yet confirmed.", "", "## Resolution plan", "", brief.plan ? `\`\`\`json\n${JSON.stringify(brief.plan, null, 2)}\n\`\`\`` : "No plan saved.", "", `**Plan validation:** ${brief.planValidation?.readiness ?? "not available"}`, brief.planBinding ? `**Exact plan:** v${brief.planBinding.version} - \`${brief.planBinding.digest}\`` : "**Exact plan:** not yet bound", "", "## Approval", "", brief.approval ? `${brief.approval.status} at ${brief.approval.approvedAt}. ${brief.approval.rationale}` : "DRAFT — no approval has been recorded.", "", "## Human authority", "", brief.humanAuthorityStatement, ""].join("\n");
}
export function renderDecisionBriefJson(brief: DecisionBrief): string { return `${JSON.stringify(brief, null, 2)}\n`; }
